config/routes.rb
CodeAnswers::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'users#destroy', as: 'logout'

  root :to => 'users#home'

  resources :users do
    resources :questions do
      resources :answers do
        resources :votes, :only => [:create]
      end
      resources :votes, :only => [:create]
    end
  end
  resources :sessions


end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes, :as => :votable
end

app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :votes, :as => :votable
end

app/models/question_vote.rb
class QuestionVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :votes

  has_secure_password
  # validates :password_confirmation, :presence => true
  validates :name, :presence => true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, :presence => true, :uniqueness => true

  validates :email,
            :presence => true,
            :uniqueness => { case_sensitive: false },
            :format => { with: VALID_EMAIL_REGEX }
  validates :password, :presence => true
  validates :password_digest, :presence => true

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer, polymorphic: true
  belongs_to :question, polymorphic: true
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def create
    question = Question.find(params[:question_id])
    user = User.find(question.user_id)
    @answer = Answer.create(answer_params)
    respond_to do |format|
      format.html { redirect_to user_question_path(user, question) }
      format.js
    end
  end

  private

    def answer_params
      params.require(:answer).permit(:message, :user_id, :question_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   private
    def current_user
      current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to :root
    else
      render 'new'
    end

  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @vote = Vote.new
    @best_answer = Answer.find(@question.best_answer_id)
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private
    def question_params
      params.require(:question).permit(:title, :message, :best_answer_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to :root, notice: 'Logged In!'
    else
      flash.now.alert = "Email or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
    @questions = Question.all

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to :root, notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @vote = @question.votes.create(vote_params)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end


  private
    def vote_params
      params.require(:vote).permit(:vote_value, :user_id, :votable_id, :votable_type)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<div class="q-answer">
    <%= @answer.message %>
  <span class="a-author">Submitted by <%= @answer.user.name %></span>
</div>

app/views/answers/create.js.erb
  $('#answers').append('<%= j render(@answer) %>');

app/views/answers/index.html.erb
<h2><%=  @question.title %></h2>
<pre><%= @question.message %></pre>

<div id="answers">
  <% @answers.each do |answer| %>
    <div class="q-answer">
      <%= answer.message %>
      <span class="a-author">Submitted by <%= answer.user.name %></span>
    </div>
  <% end %>
</div>

<%= form_for [current_user, @question, @answer], :role => 'form', :remote => true do |f| %>
  <div class="form-group">
    <%= f.text_area :message, id: 'answer-ta', class: 'form-control', placeholder: 'Add Answer' %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :question_id, value: @question.id %>

  <%= f.submit "Submit", :class => 'btn btn-info' %>

<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
      <div class="naviHeader">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse navHeaderCollapse">
            <ul class="nav navbar-nav navbar-left">
              <li><a href="/">Code Q&amp;A</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
               <li><%= link_to current_user.name, user_path(current_user) %></li>
               <li><%= link_to 'Logout', session_path('current'), method: 'delete' %></li>
              <% else %>
                <li><%= link_to 'Login', new_session_path %></li>
                <li><%= link_to 'Register', new_user_path %><li>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeAnswers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container" id="content">
  <%= yield %>
</div>

</body>
</html>

app/views/questions/new.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md-6">
      <h1>New Question</h1>

      <%= form_for [current_user, @question], role: 'form' do |f| %>
        <% if @question.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% @question.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title, 'Title:', class: 'sr-only' %>
          <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.text_area :message, id: 'question-ta', class: 'form-control' %>
        </div>
        <%= f.submit "Submit", :class => 'btn btn-info' %>
      <% end %>

    </div>
  </div>

</div>

app/views/questions/show.html.erb
<h2><%=  @question.title %></h2>
<div class="vote">

    <%= form_for [current_user, @question, @vote], :role => 'form', :remote => true do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :vote_value, value: '1' %>
      <span class='glyphicon glyphicon-chevron-up'></span>
    <% end %>

    <span class="vote-count-post"><% sum = 0 %>
                                  <% @question.votes.each {|v| sum += v.vote_value } %>
                                  <%= sum %></span>
    <%= form_for [current_user, @question, @vote], :role => 'form', :remote => true do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :vote_value, value: '-1' %>
      <span class='glyphicon glyphicon-chevron-down'></span>
    <% end %>

</div>
<pre><%= @question.message %></pre>
<div class="clear"></div>
<hr>
<div id="best-answer">
  <span class='glyphicon glyphicon-heart'></span>
  <%= @best_answer.message %>
  <span class="a-author">Submitted by <%= @best_answer.user.name %></span>
</div>
<hr>

<div id="answers">
  <% @question.answers.each do |answer| %>
  <% unless answer.id == @question.best_answer_id %>
    <div class="q-answer">
      <% if @question.user_id = current_user.id %>
      <%= form_for [current_user, @question], :role => 'form', :remote => true do |f| %>
      <%= f.hidden_field :best_answer_id, value: answer.id %>
      <span class='glyphicon glyphicon-heart'></span>
    <% end %>
    <% end %>
      <%= answer.message %>
      <span class="a-author">Submitted by <%= answer.user.name %></span>
    </div>
    <hr>
    <% end %>

  <% end %>
</div>
<%= form_for [current_user, @question, @answer], :role => 'form', :remote => true do |f| %>
  <div class="form-group">
    <%= f.text_area :message, id: 'answer-ta', class: 'form-control', placeholder: 'Add Answer' %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :question_id, value: @question.id %>

  <%= f.submit "Submit", :class => 'btn btn-info' %>

<% end %>

app/views/users/home.html.erb
<% if current_user %>
  <p>Welcome <%= current_user.name %></p>
<% end %>
<h1>Welcome to Code Q&amp;A</h1>

<div class="col-md-6">
  <h4>Questions</h4>

  <% @questions.each do |question| %>
    <div class="home-question">

      <%= link_to question.title, user_question_path(question.user_id, question) %>
      <% if current_user && question.user_id != current_user.id %>

        <%= link_to '+ Answer', user_question_path(current_user, question) %>
      <% end %>
    </div>
  <% end %>
</div>
<hr>
  <% if current_user %>
    <%= link_to 'Add Question', new_user_question_path(current_user) %>
  <% end %>

app/views/users/new.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md-6">
      <h1>Sign Up </h1>

      <%= form_for @user, role: 'form' do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, 'Full Name:', class: 'sr-only' %>
          <%= f.text_field :name, placeholder: 'Full Name', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, 'Email:', class: 'sr-only' %>
          <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, 'Password:', class: 'sr-only' %>
          <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, 'Password Confirm:', class: 'sr-only' %>
          <%= f.password_field :password_confirmation, placeholder: 'Password Confirm', class: 'form-control' %>
        </div>
        <%= f.submit "Register", :class => 'btn btn-info' %>
      <% end %>

    </div>
  </div>

</div>

app/views/users/show.html.erb
<h3><%= current_user.name %></h3>
  <h5>User since: <%= time_ago_in_words(current_user.created_at) %> ago</h5>

<div class="col-md-6">
  <h4>Your questions</h4>
  <%= link_to 'Add Question', new_user_question_path(current_user) %>
  <% current_user.questions.each do |question| %>
    <div class="home-question">

      <%= question.title %>
    </div>
  <% end %>
</div>
<div class="col-md-6">
  <h4>Your answers</h4>
  <% if false %>
  <%= link_to 'Add Question', new_user_question_path(current_user) %>
  <% @questions.each do |question| %>
    <div class="home-question">
      <%= question.title %>
    </div>
  <% end %>
  <% end %>
</div>

app/views/votes/_vote.html.erb
<% sum = 0 %>
<% @question.votes.each {|v| sum += v.vote_value } %>
<%= sum %>

app/views/votes/create.js.erb
current_count = parseInt($('.vote-count-post').text())
$('.vote-count-post').text('<%= j render(@vote) %>')